#include <bits/stdc++.h>
using namespace std;
#define rep(i,n) for (int i = 0; i < (n); ++i)
typedef long long ll;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S){
    string ans="Yes";
    rep(i,S.length()){
        if(S[i]=='R' and i%2!=0){
            ans="No";
            break;
        }
        if(S[i]=='L' and i%2==0){
            ans="No";
            break;
        }
    }
    cout<<ans<<endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
