#include <bits/stdc++.h>
using namespace std;
#define rep(i,n) for (int i = 0; i < (n); ++i)
typedef long long ll;

const long long MOD = 998244353;

void solve(long long N, std::vector<long long> D){
    ll ans=1,f=1;
    sort(D.begin(),D.end());
    rep(i,N){
        if(i>0 and D[i]-D[i-1]>1)f=0;
    }
    vector<ll> cnt(100001);
    rep(i,100001) cnt[i]=0;
    rep(i,N) cnt[D[i]]++;
    if(cnt[0]!=1)f=0;
    rep(i,N){
        if(i>0){
            ans=(ans*cnt[D[i]-1])%MOD;
        }
    }
    ans%=MOD;
    cout<<(f?ans:0)<<endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cout<<std::fixed<<std::setprecision(10);//誤差小数10桁まで
    long long N;
    scanf("%lld",&N);
    std::vector<long long> D(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&D[i]);
    }
    solve(N, std::move(D));
    return 0;
}
