#include <bits/stdc++.h>
using namespace std;
#define rep(i,n) for (int i = 0; i < (n); ++i)
typedef long long ll;



void solve(long long N, std::vector<long long> L){
    sort(L.begin(),L.end());
    ll ans=0;
    int i=N-1;
    while(i>1){
        int j=i-1;
        while(j>0){
            ll r=j-1,l=-1;
            ll c=(l+r)/2;
            while(l+1<r){
                (L[i]+L[j]>L[c]) ? l=c : r=c;
            }
            ans+=c;
            j--;
        }
        i--;
    }
    cout<<ans<<endl;
}   

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cout<<std::fixed<<std::setprecision(10);//誤差小数10桁まで
    long long N;
    scanf("%lld",&N);
    std::vector<long long> L(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&L[i]);
    }
    solve(N, std::move(L));
    return 0;
}
