#include <bits/stdc++.h>
using namespace std;
#define rep(i,n) for (int i = 0; i < (n); ++i)
typedef long long ll;

void solve(string S){
    rep(i,1<<(S.length()-1)){
        ll num=S[0]-'0';
        rep(j,S.length()-1){
            
        }
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::cout<<std::fixed<<std::setprecision(10);//誤差小数10桁まで
    string S="2+1";
    cout<<stol(S);
    return 0;
}
